name: Test Browser Headful

on:
  workflow_dispatch:
    inputs:
        login-only:
          type: boolean
          default: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out browser script
        uses: actions/checkout@v4
        with:
          repository: 'AariaX/Microsoft-Rewards-Script'
          ref: 'v3'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create accounts.json from secret üìù
        run: |
          cat << 'EOF' > src/accounts.json
          ${{ secrets.ACCOUNTS_JSON }}
          EOF

      - name: Modify config.json ‚öôÔ∏è
        run: |
          cat << 'EOF' > src/config.json
          ${{ secrets.CONFIG }}
          EOF

      - name: Install dependencies
        run: npm i

      - name: Install Playwright Browsers & Dependencies üåê
        run: npx patchright install chromium-headless-shell --with-deps

      - name: Build the project üèóÔ∏è
        run: npm run build

      - name: Cache and Restore Sessions üíæ
        uses: actions/cache@v4
        with:
          path: dist/browser/sessions
          key: ${{ runner.os }}-sessions-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-sessions-

      - name: Start the test üñ•Ô∏è
        run: |
          npm start > /dev/null 2>&1
        env:
          TZ: Asia/Bangkok
          LOGIN_ONLY: ${{ inputs.login-only && 'true' || '' }}
