name: Test Browser Headful

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out browser script
        uses: actions/checkout@v4
        with:
          repository: 'AariaX/Microsoft-Rewards-Script'
          ref: 'v3'

      - name: Cache and Restore Sessions ğŸ’¾
        uses: actions/cache@v4
        with:
          path: dist/browser/sessions
          key: ${{ runner.os }}-sessions-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-sessions-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create accounts.json from secret ğŸ“
        run: |
          cat << 'EOF' > src/accounts.json
          ${{ secrets.ACCOUNTS_JSON }}
          EOF

      - name: Modify config.json âš™ï¸
        run: |
          cat << 'EOF' > src/config.json
          ${{ secrets.CONFIG }}
          EOF

      - name: Install dependencies
        run: npm i

      - name: Install Playwright Browsers & Dependencies ğŸŒ
        run: npx playwright install chromium --with-deps

      - name: Build the project ğŸ—ï¸
        run: npm run build

      - name: Start virtual display ğŸ–¥ï¸
        run: |
          Xvfb :99 &
          DISPLAY=:99 npm start > /dev/null 2>&1
